### PR TITLE
Stop Visual Studio Code from freaking out when seeing Flow code

### PR DESCRIPTION
**Pull request by mishaor**
Visual Studio Code detects errors in this project's source code. Because Visual Studio Code doesn't have built-in Flow support, it will instead validate the obviously not pure JavaScript code... with a JavaScript validator. This pull request disables the built-in JavaScript validator using a file named `settings.json` (contains settings for this specific project). (Note: it doesn't affect basic JavaScript validator, only the rich language support one).

### CODE REVIEW

**Comment by mishaor** [comment]
(this isn't even a pull request description, but an entire essay on problems with Flow and VSCode lol)

**Comment by mishaor** [comment]
Helloooo! Anyone here?

**Comment by bvaughn** [comment]
I've just added `.vscode` to the `.gitignore` list. I don't really want to start adding editor config files to this repo. 👍

**Comment by mishaor** [comment]
welp, vscode users are left for eternal suffering

**Pull request closed without merging**
