### PR TITLE
Improve performance by mutating the children array

### PR DESCRIPTION
**Pull request by gaearon**
I'm seeing ~15% improvement for additions in ~20% improvement for deletions on huge trees with this change. Probably because we copy less and because we don't churn the GC as much.

### CODE REVIEW

**Comment by bvaughn** [comment]
> I'm seeing ~15% improvement for additions in ~20% improvement for deletions on huge trees with this change.

Neat. What are the absolute numbers?

**Comment by gaearon** [comment]
With thousands of nodes, I was seeing something like 85ms -> 73ms and 32ms -> 25ms for time spent in add and remove, respectively.

**Comment by bvaughn** [comment]
Nice!

**Comment by gaearon** [comment]
That said in general GC churn accumulates and causes pauses even if each individual operation doesn't take that long.

**Pull request merged**
